# Generated by Django 6.0.7 on 2026-09-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('word_count', models.IntegerField()),
                ('character_count', models.IntegerField()),
                ('sentence_count', models.IntegerField()),
                ('word_frequencies', models.TextField()),
                ('readability_score', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
